import 'package:adventofcode/adventofcode2024.dart';
import 'package:adventofcode/src/utils.dart';
import 'package:test/test.dart';

void main() {
  const input = Input('''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............''');

  test('first star', () {
    expect(day08star1(input), equals(14));
  });
  test('second star', () {
    expect(day08star2(input), equals(34));
  });
}
